### ISSUE TITLE
Wrong error code when there is no SNMP community

### ISSUE THREAD

**Issue by leonardobdes** [leonardobdes/BIGdiff#1]
@Torsten Sorger
The script will fail if no SNMP communities exist on the BigIP (exit code 5 - Failure to run snmpwalk).

@jaikumar_f5
Hi Leo,

Was testing this on couple of servers, noticed when there is no SNMP community strings configured, the error that should be captured is e_no_snmp_community(4), but the error getting capture is e_running_snmpwalk(5).

Because irrespective of get_snmp_community() success or not, run_snmpwalk() is getting always triggered. Then "Failure to run snmpwalk" error is coming up.

Would you want to update it to get "There is no SNMP community setup" when there's no SNMP community configured and stop further processing.

**Comment by leonardobdes** [comment]
Fixed in version 1.1.0.

**Comment by jba3126** [comment]
When I ran the script it produced a .txt file vs .html.  I renamed the file and ensured that it was in the same folder as the tablefilter.js; however it comes out as text in a browser.  The data is present, just not formatted correctly for HTML viewing

This is the first line of the output file.

F5-BIGIP-LOCAL-MIB::ltmVsStatusEnabledState."/TR/RP-DR-TR-80" enabled


/jeff

**Comment by leonardobdes** [comment]
You need to run the script twice, before and after. 3 files will be produced, 2 txt and one html. The line you post is from the txt file.
If you still have problems, please open a new issue, and I will have a look.
